### ISSUE TITLE
Keyboard press and write does not work.

### ISSUE THREAD

**Issue by gKreator** [ZenLulz/MemorySharp#14]
It seems like the Keyboard press and write does not work. I tried this with both Notepad and Notepad++. Does anyone know of a fix for this? Thanks!

Using Version 1.2 of MemorySharp.
Windows 10 x64
VS2017

> using System;
> using System.Collections.Generic;
> using System.ComponentModel;
> using System.Data;
> using System.Drawing;
> using System.Linq;
> using System.Text;
> using System.Threading.Tasks;
> using System.Windows.Forms;
> using Binarysharp.MemoryManagement;
> using System.Diagnostics;
> 
> namespace memsharp_test_1
> {
>     public partial class Form1 : Form
>     {
>         public Form1()
>         {
>             InitializeComponent();
>         }
> 
>         private void Form1_Load(object sender, EventArgs e)
>         {
>             var sharp = new MemorySharp(Process.GetCurrentProcess());
> 
>             var tlsPtr = sharp.Threads.MainThread.Teb.Tls;
> 
>             Console.WriteLine(tlsPtr.ToString());
> 
>             var wh = sharp.Windows.GetWindowsByTitleContains("Notepad").FirstOrDefault();
> 
>             Console.WriteLine(wh.ToString());
> 
>             wh.Keyboard.Press(Binarysharp.MemoryManagement.Native.Keys.A); // does nothing
>             wh.Keyboard.PressRelease(Binarysharp.MemoryManagement.Native.Keys.A); // does nothing
> 
>             wh.Width = 800; // works
>             wh.Height = 600; // works
> 
>             wh.Keyboard.Write("test 123"); // does nothing
> 
>         }
>     }
> }

**Comment by madebyvince** [comment]
Hi,
I'm having the exact same issue and haven't been able to find a solution so far...
Is there anyone who can help???
Thanks.

**Comment by JamesMenetrey** [comment]
Hey dudes !

You have the exact code to send keys to Notepad++ in the README of the project. 🙄 

Look at the section called _Query/interact with windows_. To send inputs, you need to target _Window_. In the instance of Notepad++, you need to select the component _Scintilla_.

Cheers,
ZenLulz
