### ISSUE TITLE
equivalent to ReadProcessMemory

### ISSUE THREAD

**Issue by AtefR** [ZenLulz/MemorySharp#19]
I've been trying to achieve this code with MemorySharp read with address and pointer but without success,

`byte[] object_pointer = new byte[4];

int bytesRead;

var objAddress = Base + 0x4C5F4C;

ReadProcessMemory(App.GameProcess.Process.Handle, objAddress, object_pointer, 4, out bytesRead);`

but i get `The relative address cannot be greater than the main module size.`

I tried this
`IntPtr objectPointer = sharp.Read<IntPtr>(Base + 0x4C5F4C);`

The problem is there's a pointer stored on memory address i want to read that pointer from the address, the code above works but i have to write more code to change from byte[] to IntPtr to use it again on assembly transaction.

**Comment by AtefR** [comment]
the solution was add false as second param
IntPtr objectPointer = sharp.Read<IntPtr>(Base + 0x4C5F4C, false);
fml

**Comment by JamesMenetrey** [comment]
Hey @VincentAA,

This is correct!

Cheers
