### ISSUE TITLE
System.ApplicationException

### ISSUE THREAD

**Issue by CodexOne03** [ZenLulz/MemorySharp#21]
I'm trying to write an external hack, but can't seem to make it work.
Here's the error message:
`
System.ApplicationException: Couldn't get the information from the process, error code '-1073741820'.
   in Binarysharp.MemoryManagement.Memory.MemoryCore.NtQueryInformationProcess(SafeMemoryHandle processHandle)
   in Binarysharp.MemoryManagement.MemorySharp..ctor(Process process)
   in Invoker.Program.Main(String[] args) in source\repos\Invoker\Invoker\Program.cs:row 18
`

And [here](https://pastebin.com/mHXaMHT9)'s the code

**Comment by JamesMenetrey** [comment]
Hey!

~~I waited almost one year to see if you were still using MemorySharp!~~

I'm very sorry for that horrible delay! Chances are that you already solved your issue (or changed your lib!), but in the current state, MemorySharp does not support (yet) 64-bit process, which may be the architecture of your target process.

Nonetheless, I am still planning to update it to bring x86-64 support very soon<sup>tm</sup>!

Cheers!
Jämes
