### ISSUE TITLE
Calling a thiscall function?

### ISSUE THREAD

**Issue by splatert** [ZenLulz/MemorySharp#23]
How do you call a thiscall function? I know the function's address and the 'this' pointer but when I call it like 'sharp.Assembly.Execute((IntPtr)0x0123, CallingConventions.Thiscall, (IntPtr)0x0123);', the program crashes.

**Comment by splatert** [comment]
Little help?

**Comment by JamesMenetrey** [comment]
Hey!

According to [ThiscallCallingConvention](https://github.com/JamesMenetrey/MemorySharp/blob/master/src/MemorySharp/Assembly/CallingConvention/ThiscallCallingConvention.cs), it injects a payload of assembly script, moving the function pointer into the ECX register and the additional parameters on the stack.

The first parameter must be the location of the function to execute into the target process (not sure you need that third argument, unless the function expects one parameter). 

If you still cannot make it work, check the assembly code generated by MemorySharp, to see if you can spot any issues.

Cheers
