### ISSUE TITLE
Have you translated the following C + + code?VirtualAlloc

### ISSUE THREAD

**Issue by bbhxwl** [ZenLulz/MemorySharp#25]
https://github.com/Zakaria-Master/Pasting.win-PUBG/blob/main/function.h#L27

I need to apply for memory and write data into memory. C # do not know how to use
Can the following code replace it?

```
IntPtr addr =Marshal.AllocHGlobal(100);
var bytes=System.Text.Encoding.UTF8.GetBytes("测试");
Marshal.Copy(bytes,0,addr,bytes.Length);
```

**Comment by JamesMenetrey** [comment]
You can rewrite that code using MemorySharp, but you need to invoke the primitives of an instance of `MemorySharp` (look for `Read` and `Write` in the README of the project). I highly recommend you to be more familiar with C# before proceeding.

Cheers
