### ISSUE TITLE
v1.1.1.0 is not available on nuget.org

### ISSUE THREAD

**Issue by colemickens** [ZenLulz/MemorySharp#7]
The package on nuget.org contains a DLL marked v1,1,0.0. I can't get this DLL to work. I get runtime exception:

    {"Couldn't get the information from the process, error code '-1073741820'."}

But if I use v1.1.1.0 manually, without nuget, then it works fine.

Can you piblish 1.1.1.0 to nuget? Thanks!

**Comment by ZenLulz** [comment]
Hey @colemickens,

Did you try to open a 64-bit process ? MemorySharp does not support 64-bit yet. :)

I'm going to publish the latest version of MemorySharp this week-end on nuget.

Cheers,
Zen

**Comment by colemickens** [comment]
I think it may be opening a 64 bit project.

Like I said though, v1.1.1.0 binary works fine, where as the 1.1.0.0 doesn't. I can't really explain it.

This is for use in Snaacky/H5Tweak. The DLL (v1.1.**1**.0) is checked in over there and it works, but if I switch it to using nuget to pull v1.1.**0**.0, it gets the error above.

**Comment by ZenLulz** [comment]
Hi @colemickens,

MemorySharp V1.2 has been published right now !

Let me know if you encounter any issue.

Cheers
Zen
